print("   _______________")
print("8 |R|K|B|Q|X|B|K|R|")
print("7 |P|P|P|P|P|P|P|P|")
print("6 |·|·|·|·|·|·|·|·|")
print("5 |·|·|·|·|·|·|·|·|")
print("4 |·|·|·|·|·|·|·|·|")
print("3 |·|·|·|·|·|·|·|·|")
print("2 |p|p|p|p|p|p|p|p|")
print("1 |r|k|b|q|x|b|k|r|")
print("   ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print("   a b c d e f g h")